<?php

namespace AppBundle\Repository;

/**
 * anexo5_arrendamiento_espaciosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class anexo5_arrendamiento_espaciosRepository extends \Doctrine\ORM\EntityRepository
{
}
