<?php

namespace AppBundle\Repository;

/**
 * anexo1_contrato_mantenimiento_pizarra_pbxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class anexo1_contrato_mantenimiento_pizarra_pbxRepository extends \Doctrine\ORM\EntityRepository
{
}
