<?php

namespace AppBundle\Repository;

/**
 * anexo2_contrato_arrendamiento_redesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class anexo2_contrato_arrendamiento_redesRepository extends \Doctrine\ORM\EntityRepository
{
}
