<?php

namespace AppBundle\Repository;

/**
 * anexocps_servicios_tercerosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class anexocps_servicios_tercerosRepository extends \Doctrine\ORM\EntityRepository
{
}
