<?php

namespace AppBundle\Repository;

/**
 * anexo3_contrato_agenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class anexo3_contrato_agenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
