<?php

namespace AppBundle\Repository;

/**
 * anexo1_contrato_arrendamiento_espaciosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class anexo1_contrato_arrendamiento_espaciosRepository extends \Doctrine\ORM\EntityRepository
{
}
