<?php

namespace AppBundle\Repository;

/**
 * anexocps_levantamiento_redes_tecnicasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class anexocps_levantamiento_redes_tecnicasRepository extends \Doctrine\ORM\EntityRepository
{
}
