<?php

namespace AppBundle\Repository;

/**
 * anexocps_conexion_centrales_telefonicasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class anexocps_conexion_centrales_telefonicasRepository extends \Doctrine\ORM\EntityRepository
{
}
