<?php

namespace AppBundle\Repository;

/**
 * anexo1_contrato_compra_venta_pizarraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class anexo1_contrato_compra_venta_pizarraRepository extends \Doctrine\ORM\EntityRepository
{
}
