<?php

namespace AppBundle\Repository;

/**
 * anexo4_contrato_recarga_por_posRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class anexo4_contrato_recarga_por_posRepository extends \Doctrine\ORM\EntityRepository
{
}
