<?php

namespace AppBundle\Repository;

/**
 * anexo2_contrato_instalacion_pizarra_pbxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class anexo2_contrato_instalacion_pizarra_pbxRepository extends \Doctrine\ORM\EntityRepository
{
}
