<?php

namespace AppBundle\Repository;

/**
 * anexo5_contrato_areas_internetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class anexo5_contrato_areas_internetRepository extends \Doctrine\ORM\EntityRepository
{
}
