<?php

namespace AppBundle\Repository;

/**
 * contrato_prestacion_serviciosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contrato_prestacion_serviciosRepository extends \Doctrine\ORM\EntityRepository
{
}
