<?php

namespace AppBundle\Repository;

/**
 * contrato_agencia_persona_juridicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contrato_agencia_persona_juridicaRepository extends \Doctrine\ORM\EntityRepository
{
}
