<?php

namespace AppBundle\Repository;

/**
 * contrato_compra_ventaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contrato_compra_ventaRepository extends \Doctrine\ORM\EntityRepository
{
}
