<?php

namespace AppBundle\Repository;

/**
 * contrato_comp_vent_pizarraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contrato_comp_vent_pizarraRepository extends \Doctrine\ORM\EntityRepository
{
}
