<?php

namespace AppBundle\Repository;

/**
 * contrato_prestacion_servicios_contactos_telefonicosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contrato_prestacion_servicios_contactos_telefonicosRepository extends \Doctrine\ORM\EntityRepository
{
}
