<?php

namespace AppBundle\Repository;

/**
 * contrato_compra_venta_pizarra_pbxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contrato_compra_venta_pizarra_pbxRepository extends \Doctrine\ORM\EntityRepository
{
}
