<?php

namespace AppBundle\Repository;

/**
 * datos_cuentas_bancarias_etecsaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class datos_cuentas_bancarias_etecsaRepository extends \Doctrine\ORM\EntityRepository
{
}
