<?php

namespace AppBundle\Repository;

/**
 * descripcion_productos_serviciosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class descripcion_productos_serviciosRepository extends \Doctrine\ORM\EntityRepository
{
}
