<?php

namespace AppBundle\Repository;

/**
 * equipamiento_gsm_posRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class equipamiento_gsm_posRepository extends \Doctrine\ORM\EntityRepository
{
}
