<?php

namespace AppBundle\Repository;

/**
 * facilidades_del_equipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class facilidades_del_equipoRepository extends \Doctrine\ORM\EntityRepository
{
}
