<?php

namespace AppBundle\Repository;

/**
 * grupos_electrogenosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class grupos_electrogenosRepository extends \Doctrine\ORM\EntityRepository
{
}
