<?php

namespace AppBundle\Repository;

/**
 * localesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class localesRepository extends \Doctrine\ORM\EntityRepository
{
}
