<?php

namespace AppBundle\Repository;

/**
 * mantenimiento_preventivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class mantenimiento_preventivoRepository extends \Doctrine\ORM\EntityRepository
{
}
