<?php

namespace AppBundle\Repository;

/**
 * mantenimiento_correctivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class mantenimiento_correctivoRepository extends \Doctrine\ORM\EntityRepository
{
}
