<?php

namespace AppBundle\Repository;

/**
 * pizarra_pbxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pizarra_pbxRepository extends \Doctrine\ORM\EntityRepository
{
}
