<?php

namespace AppBundle\Repository;

/**
 * protecciones_tierraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class protecciones_tierraRepository extends \Doctrine\ORM\EntityRepository
{
}
