<?php

namespace AppBundle\Repository;

/**
 * relacion_iluminacion_tomacorrienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class relacion_iluminacion_tomacorrienteRepository extends \Doctrine\ORM\EntityRepository
{
}
