<?php

namespace AppBundle\Repository;

/**
 * relacion_terminaciones_bastidorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class relacion_terminaciones_bastidorRepository extends \Doctrine\ORM\EntityRepository
{
}
