<?php

namespace AppBundle\Repository;

/**
 * relacion_viasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class relacion_viasRepository extends \Doctrine\ORM\EntityRepository
{
}
