<?php

namespace AppBundle\Repository;

/**
 * relacion_mastiles_a4Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class relacion_mastiles_a4Repository extends \Doctrine\ORM\EntityRepository
{
}
