<?php

namespace AppBundle\Repository;

/**
 * relacion_distancia_arrendada_soterradoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class relacion_distancia_arrendada_soterradoRepository extends \Doctrine\ORM\EntityRepository
{
}
