<?php

namespace AppBundle\Repository;

/**
 * sistema_corriente_directaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sistema_corriente_directaRepository extends \Doctrine\ORM\EntityRepository
{
}
