<?php

namespace AppBundle\Repository;

/**
 * sistemas_corriente_alternaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sistemas_corriente_alternaRepository extends \Doctrine\ORM\EntityRepository
{
}
