<?php

namespace AppBundle\Repository;

/**
 * sistema_iluminacion_a5Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sistema_iluminacion_a5Repository extends \Doctrine\ORM\EntityRepository
{
}
