<?php

namespace AppBundle\Repository;

/**
 * tarifas_espacios_arrendadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tarifas_espacios_arrendadosRepository extends \Doctrine\ORM\EntityRepository
{
}
