<?php

namespace AppBundle\Repository;

/**
 * tarifas_conexion_pizarrasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tarifas_conexion_pizarrasRepository extends \Doctrine\ORM\EntityRepository
{
}
