<?php

namespace AppBundle\Repository;

/**
 * tarjetas_simRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tarjetas_simRepository extends \Doctrine\ORM\EntityRepository
{
}
