<?php

namespace AppBundle\Repository;

/**
 * terminacionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class terminacionesRepository extends \Doctrine\ORM\EntityRepository
{
}
