<?php

namespace AppBundle\Repository;

/**
 * tipos_mantenimientos_correctivosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tipos_mantenimientos_correctivosRepository extends \Doctrine\ORM\EntityRepository
{
}
