<?php

namespace AppBundle\Repository;

/**
 * tipos_de_mantenimientosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tipos_de_mantenimientosRepository extends \Doctrine\ORM\EntityRepository
{
}
