<?php

namespace AppBundle\Repository;

/**
 * tipos_distancias_arrendadasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tipos_distancias_arrendadasRepository extends \Doctrine\ORM\EntityRepository
{
}
