<?php

namespace AppBundle\Repository;

/**
 * tomacorrientesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tomacorrientesRepository extends \Doctrine\ORM\EntityRepository
{
}
