<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Empresa extends \AppBundle\Entity\Empresa implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'organismo', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'personas', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'contratoAgencia', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'contratoAreas', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'contrato_arrendamiento_pizarra', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'contratoArrendamientoRedes', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'contratoCompraVenta', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'contratoCompraVentaPizarra', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'contratoInstalacionPizarra', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'contratoMantenimientoPizarra', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'contratoPrestacionServicios', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'contratoPrestacionServiciosCT', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'contratoRecargaPOS', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'codigoREUP', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'nombreOficial', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'nombreAbreviado', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'domicilio', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'actividadEconomica', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'correoElectronico', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'sitioWeb', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'observaciones', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'nOCuentaBancariaMLC', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'nOCuentaBancariaMN'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'organismo', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'personas', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'contratoAgencia', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'contratoAreas', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'contrato_arrendamiento_pizarra', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'contratoArrendamientoRedes', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'contratoCompraVenta', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'contratoCompraVentaPizarra', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'contratoInstalacionPizarra', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'contratoMantenimientoPizarra', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'contratoPrestacionServicios', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'contratoPrestacionServiciosCT', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'contratoRecargaPOS', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'codigoREUP', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'nombreOficial', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'nombreAbreviado', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'domicilio', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'actividadEconomica', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'correoElectronico', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'sitioWeb', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'observaciones', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'nOCuentaBancariaMLC', '' . "\0" . 'AppBundle\\Entity\\Empresa' . "\0" . 'nOCuentaBancariaMN'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Empresa $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigoREUP($codigoREUP)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigoREUP', [$codigoREUP]);

        return parent::setCodigoREUP($codigoREUP);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigoREUP()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigoREUP', []);

        return parent::getCodigoREUP();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreOficial($nombreOficial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreOficial', [$nombreOficial]);

        return parent::setNombreOficial($nombreOficial);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreOficial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreOficial', []);

        return parent::getNombreOficial();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreAbreviado($nombreAbreviado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreAbreviado', [$nombreAbreviado]);

        return parent::setNombreAbreviado($nombreAbreviado);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreAbreviado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreAbreviado', []);

        return parent::getNombreAbreviado();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomicilio($domicilio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomicilio', [$domicilio]);

        return parent::setDomicilio($domicilio);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomicilio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomicilio', []);

        return parent::getDomicilio();
    }

    /**
     * {@inheritDoc}
     */
    public function setActividadEconomica($actividadEconomica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActividadEconomica', [$actividadEconomica]);

        return parent::setActividadEconomica($actividadEconomica);
    }

    /**
     * {@inheritDoc}
     */
    public function getActividadEconomica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActividadEconomica', []);

        return parent::getActividadEconomica();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorreoElectronico($correoElectronico)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorreoElectronico', [$correoElectronico]);

        return parent::setCorreoElectronico($correoElectronico);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorreoElectronico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorreoElectronico', []);

        return parent::getCorreoElectronico();
    }

    /**
     * {@inheritDoc}
     */
    public function setSitioWeb($sitioWeb = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSitioWeb', [$sitioWeb]);

        return parent::setSitioWeb($sitioWeb);
    }

    /**
     * {@inheritDoc}
     */
    public function getSitioWeb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSitioWeb', []);

        return parent::getSitioWeb();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservaciones($observaciones = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservaciones', [$observaciones]);

        return parent::setObservaciones($observaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservaciones', []);

        return parent::getObservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setNOCuentaBancariaMLC($nOCuentaBancariaMLC)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNOCuentaBancariaMLC', [$nOCuentaBancariaMLC]);

        return parent::setNOCuentaBancariaMLC($nOCuentaBancariaMLC);
    }

    /**
     * {@inheritDoc}
     */
    public function getNOCuentaBancariaMLC()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNOCuentaBancariaMLC', []);

        return parent::getNOCuentaBancariaMLC();
    }

    /**
     * {@inheritDoc}
     */
    public function setNOCuentaBancariaMN($nOCuentaBancariaMN)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNOCuentaBancariaMN', [$nOCuentaBancariaMN]);

        return parent::setNOCuentaBancariaMN($nOCuentaBancariaMN);
    }

    /**
     * {@inheritDoc}
     */
    public function getNOCuentaBancariaMN()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNOCuentaBancariaMN', []);

        return parent::getNOCuentaBancariaMN();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrganismo(\AppBundle\Entity\Organismos $organismo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrganismo', [$organismo]);

        return parent::setOrganismo($organismo);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganismo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganismo', []);

        return parent::getOrganismo();
    }

    /**
     * {@inheritDoc}
     */
    public function addPersona(\AppBundle\Entity\Personas $persona)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPersona', [$persona]);

        return parent::addPersona($persona);
    }

    /**
     * {@inheritDoc}
     */
    public function removePersona(\AppBundle\Entity\Personas $persona)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePersona', [$persona]);

        return parent::removePersona($persona);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonas', []);

        return parent::getPersonas();
    }

    /**
     * {@inheritDoc}
     */
    public function addContratoAgencium(\AppBundle\Entity\contrato_agencia_persona_juridica $contratoAgencium)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContratoAgencium', [$contratoAgencium]);

        return parent::addContratoAgencium($contratoAgencium);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContratoAgencium(\AppBundle\Entity\contrato_agencia_persona_juridica $contratoAgencium)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContratoAgencium', [$contratoAgencium]);

        return parent::removeContratoAgencium($contratoAgencium);
    }

    /**
     * {@inheritDoc}
     */
    public function getContratoAgencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContratoAgencia', []);

        return parent::getContratoAgencia();
    }

    /**
     * {@inheritDoc}
     */
    public function addContratoArea(\AppBundle\Entity\contrato_areas_internet $contratoArea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContratoArea', [$contratoArea]);

        return parent::addContratoArea($contratoArea);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContratoArea(\AppBundle\Entity\contrato_areas_internet $contratoArea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContratoArea', [$contratoArea]);

        return parent::removeContratoArea($contratoArea);
    }

    /**
     * {@inheritDoc}
     */
    public function getContratoAreas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContratoAreas', []);

        return parent::getContratoAreas();
    }

    /**
     * {@inheritDoc}
     */
    public function addContratoArrendamientoPizarra(\AppBundle\Entity\contrato_arrendamiento_pizarra_privada_pbx $contratoArrendamientoPizarra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContratoArrendamientoPizarra', [$contratoArrendamientoPizarra]);

        return parent::addContratoArrendamientoPizarra($contratoArrendamientoPizarra);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContratoArrendamientoPizarra(\AppBundle\Entity\contrato_arrendamiento_pizarra_privada_pbx $contratoArrendamientoPizarra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContratoArrendamientoPizarra', [$contratoArrendamientoPizarra]);

        return parent::removeContratoArrendamientoPizarra($contratoArrendamientoPizarra);
    }

    /**
     * {@inheritDoc}
     */
    public function getContratoArrendamientoPizarra()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContratoArrendamientoPizarra', []);

        return parent::getContratoArrendamientoPizarra();
    }

    /**
     * {@inheritDoc}
     */
    public function addContratoArrendamientoRede(\AppBundle\Entity\contrato_arrendamiento_redes $contratoArrendamientoRede)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContratoArrendamientoRede', [$contratoArrendamientoRede]);

        return parent::addContratoArrendamientoRede($contratoArrendamientoRede);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContratoArrendamientoRede(\AppBundle\Entity\contrato_arrendamiento_redes $contratoArrendamientoRede)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContratoArrendamientoRede', [$contratoArrendamientoRede]);

        return parent::removeContratoArrendamientoRede($contratoArrendamientoRede);
    }

    /**
     * {@inheritDoc}
     */
    public function getContratoArrendamientoRedes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContratoArrendamientoRedes', []);

        return parent::getContratoArrendamientoRedes();
    }

    /**
     * {@inheritDoc}
     */
    public function addContratoCompraVentum(\AppBundle\Entity\contrato_compra_venta $contratoCompraVentum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContratoCompraVentum', [$contratoCompraVentum]);

        return parent::addContratoCompraVentum($contratoCompraVentum);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContratoCompraVentum(\AppBundle\Entity\contrato_compra_venta $contratoCompraVentum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContratoCompraVentum', [$contratoCompraVentum]);

        return parent::removeContratoCompraVentum($contratoCompraVentum);
    }

    /**
     * {@inheritDoc}
     */
    public function getContratoCompraVenta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContratoCompraVenta', []);

        return parent::getContratoCompraVenta();
    }

    /**
     * {@inheritDoc}
     */
    public function addContratoCompraVentaPizarra(\AppBundle\Entity\contrato_comp_vent_pizarra $contratoCompraVentaPizarra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContratoCompraVentaPizarra', [$contratoCompraVentaPizarra]);

        return parent::addContratoCompraVentaPizarra($contratoCompraVentaPizarra);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContratoCompraVentaPizarra(\AppBundle\Entity\contrato_comp_vent_pizarra $contratoCompraVentaPizarra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContratoCompraVentaPizarra', [$contratoCompraVentaPizarra]);

        return parent::removeContratoCompraVentaPizarra($contratoCompraVentaPizarra);
    }

    /**
     * {@inheritDoc}
     */
    public function getContratoCompraVentaPizarra()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContratoCompraVentaPizarra', []);

        return parent::getContratoCompraVentaPizarra();
    }

    /**
     * {@inheritDoc}
     */
    public function addContratoInstalacionPizarra(\AppBundle\Entity\contrato_instalacion_pizarra_pbx $contratoInstalacionPizarra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContratoInstalacionPizarra', [$contratoInstalacionPizarra]);

        return parent::addContratoInstalacionPizarra($contratoInstalacionPizarra);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContratoInstalacionPizarra(\AppBundle\Entity\contrato_instalacion_pizarra_pbx $contratoInstalacionPizarra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContratoInstalacionPizarra', [$contratoInstalacionPizarra]);

        return parent::removeContratoInstalacionPizarra($contratoInstalacionPizarra);
    }

    /**
     * {@inheritDoc}
     */
    public function getContratoInstalacionPizarra()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContratoInstalacionPizarra', []);

        return parent::getContratoInstalacionPizarra();
    }

    /**
     * {@inheritDoc}
     */
    public function addContratoMantenimientoPizarra(\AppBundle\Entity\contrato_mantenimiento_pizarra_pbx $contratoMantenimientoPizarra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContratoMantenimientoPizarra', [$contratoMantenimientoPizarra]);

        return parent::addContratoMantenimientoPizarra($contratoMantenimientoPizarra);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContratoMantenimientoPizarra(\AppBundle\Entity\contrato_mantenimiento_pizarra_pbx $contratoMantenimientoPizarra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContratoMantenimientoPizarra', [$contratoMantenimientoPizarra]);

        return parent::removeContratoMantenimientoPizarra($contratoMantenimientoPizarra);
    }

    /**
     * {@inheritDoc}
     */
    public function getContratoMantenimientoPizarra()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContratoMantenimientoPizarra', []);

        return parent::getContratoMantenimientoPizarra();
    }

    /**
     * {@inheritDoc}
     */
    public function addContratoPrestacionServicio(\AppBundle\Entity\contrato_prestacion_servicios $contratoPrestacionServicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContratoPrestacionServicio', [$contratoPrestacionServicio]);

        return parent::addContratoPrestacionServicio($contratoPrestacionServicio);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContratoPrestacionServicio(\AppBundle\Entity\contrato_prestacion_servicios $contratoPrestacionServicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContratoPrestacionServicio', [$contratoPrestacionServicio]);

        return parent::removeContratoPrestacionServicio($contratoPrestacionServicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getContratoPrestacionServicios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContratoPrestacionServicios', []);

        return parent::getContratoPrestacionServicios();
    }

    /**
     * {@inheritDoc}
     */
    public function addContratoPrestacionServiciosCT(\AppBundle\Entity\contrato_contactos_telefonicos $contratoPrestacionServiciosCT)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContratoPrestacionServiciosCT', [$contratoPrestacionServiciosCT]);

        return parent::addContratoPrestacionServiciosCT($contratoPrestacionServiciosCT);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContratoPrestacionServiciosCT(\AppBundle\Entity\contrato_contactos_telefonicos $contratoPrestacionServiciosCT)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContratoPrestacionServiciosCT', [$contratoPrestacionServiciosCT]);

        return parent::removeContratoPrestacionServiciosCT($contratoPrestacionServiciosCT);
    }

    /**
     * {@inheritDoc}
     */
    public function getContratoPrestacionServiciosCT()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContratoPrestacionServiciosCT', []);

        return parent::getContratoPrestacionServiciosCT();
    }

    /**
     * {@inheritDoc}
     */
    public function addContratoRecargaPO(\AppBundle\Entity\contrato_recarga_por_pos $contratoRecargaPO)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContratoRecargaPO', [$contratoRecargaPO]);

        return parent::addContratoRecargaPO($contratoRecargaPO);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContratoRecargaPO(\AppBundle\Entity\contrato_recarga_por_pos $contratoRecargaPO)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContratoRecargaPO', [$contratoRecargaPO]);

        return parent::removeContratoRecargaPO($contratoRecargaPO);
    }

    /**
     * {@inheritDoc}
     */
    public function getContratoRecargaPOS()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContratoRecargaPOS', []);

        return parent::getContratoRecargaPOS();
    }

}
